/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maperry' at '11/09/15 3:03 PM' with Gradle 2.4
 *
 * @author maperry, @date 11/09/15 3:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
